### ISSUE TITLE
Replace deprecated imp module with importlib

### ISSUE THREAD

**Issue by hugovk** [facelessuser/pep562#13]
This project uses the [`imp` module](https://docs.python.org/3/library/imp.html) which has been deprecated since Python 3.4 and removed in 3.12:

* Raised `PendingDeprecationWarning` since [3.4 (2014)](https://github.com/python/cpython/commit/e4f41deccf94ccc798b1eb1f44657ade66669a60)
* Raised `DeprecationWarning` since [3.5 (2015)](https://github.com/python/cpython/commit/c0d91aff9a3b91307b26e8b7c34dfbf27bbdd43a)
* Updated `DeprecationWarning` to say removal in 3.12 since [3.10 (2021)](https://github.com/python/cpython/commit/dc6d3e1e4c0c1e4b2210edab8fb4762569dc2936)
* Removal planned for [3.12](https://github.com/python/cpython/issues/98040) [(2023)](https://github.com/python/cpython/pull/98573)

Python 3.12 is [set for release on 2023-10-02](https://devguide.python.org/versions/) and this library is one of the [top 5,000 most-downloaded from PyPI](https://hugovk.github.io/top-pypi-packages/).

Please could you upgrade to use `importlib`? The [`imp` docs](https://docs.python.org/3.11/library/imp.html) have suggestions on what to use to replace each function and constant.

**Comment by facelessuser** [comment]
In general, this library should not be used as all Python versions where this is useful are now "end of life". Python 3.7+ do not need this, and even 3.7 is close to EOL.

Most libraries should only conditionally include this as a dependency if they choose to support really old Python < 3.7.

With that said it is fairly trivial to update the setup script to use `importlib` as I've done so in some other projects. I believe this will work.

```py
def get_version():
    """Get version_info without importing the entire module."""

    import importlib.util

    path = os.path.join(os.path.dirname(__file__), "pep562", "__meta__.py")
    spec = importlib.util.spec_from_file_location("__meta__", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.__version_info__._get_dev_status()
```

PRs are also welcome. If we do this, this is likely to be the last release of this project as all Python versions that depend upon this are now EOL.

**Comment by hugovk** [comment]
Thanks for the reply. I think it's acceptable to say 3.12 isn't supported.

In fact, I now see the README says this:

> Once Python 3.6 is end of life, this module will be irrelevant and will no longer receive active support.

And 3.6 has been EOL since 2021-12-23.

Feel free to close this, and thank you for your time :)
